// Requires: ImageLibrary
//
// SkinMenu - skin sets menu for Rust (uMod / Oxide).
//
// Players open a CUI menu that lets them pick a skin per item category,
// save the selection as a named "set", and apply any saved set to their
// inventory. The menu background and frame PNGs are generated by the
// companion Python / Pillow script (design_generator.py) into the
// `oxide/data/SkinMenu/design/` folder and are loaded through
// ImageLibrary.
//
// Skin catalog modes (configurable):
//   "All"      - every skin in the catalog (includes pending workshop
//                items - can be risky on EAC-strict servers).
//   "Approved" - only skins that Facepunch has approved into the game
//                (safe).
//   "Pending"  - only skins that are still pending approval (use at
//                your own risk).

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Oxide.Core;
using Oxide.Core.Plugins;
using Oxide.Game.Rust.Cui;
using UnityEngine;

namespace Oxide.Plugins
{
    [Info("SkinMenu", "Devin", "1.0.0")]
    [Description("Per-player skin set menu with CUI design generated via Python + Pillow.")]
    public class SkinMenu : RustPlugin
    {
        [PluginReference] private Plugin ImageLibrary;

        private const string MainPanel = "skinmenu.main";
        private const string ListPanel = "skinmenu.list";
        private const string PromptPanel = "skinmenu.prompt";

        private const string PermUse = "skinmenu.use";

        // Runtime UI state per player.
        private readonly Dictionary<ulong, EditorState> _editors = new Dictionary<ulong, EditorState>();

        // -------------------------------------------------------------------
        // Config
        // -------------------------------------------------------------------

        public enum SkinMode { All, Approved, Pending }

        private class PluginConfig
        {
            [JsonProperty("Command to open the menu")]
            public string Command = "skinmenu";

            [JsonProperty("Skin catalog mode (All / Approved / Pending)")]
            [JsonConverter(typeof(StringEnumConverter))]
            public SkinMode Mode = SkinMode.Approved;

            [JsonProperty("How many skins per page in the grid")]
            public int SkinsPerPage = 12;

            [JsonProperty("Auto-apply set on respawn if a set is named 'default'")]
            public bool ApplyDefaultOnRespawn = true;

            [JsonProperty("Design image file names (placed in oxide/data/SkinMenu/design/)")]
            public DesignImages Design = new DesignImages();

            public class DesignImages
            {
                [JsonProperty("Main panel background")]
                public string Background = "bg.png";

                [JsonProperty("Skin slot frame")]
                public string SlotFrame = "slot.png";

                [JsonProperty("Selected skin slot frame")]
                public string SlotFrameActive = "slot_active.png";

                [JsonProperty("Generic button background")]
                public string Button = "button.png";

                [JsonProperty("Highlighted button background")]
                public string ButtonHighlight = "button_hl.png";
            }
        }

        private PluginConfig _config;

        protected override void LoadDefaultConfig() => _config = new PluginConfig();

        protected override void LoadConfig()
        {
            base.LoadConfig();
            try
            {
                _config = Config.ReadObject<PluginConfig>() ?? new PluginConfig();
            }
            catch (Exception e)
            {
                PrintError($"Config file is corrupted, resetting to defaults: {e.Message}");
                LoadDefaultConfig();
            }

            if (_config.SkinsPerPage < 1)
            {
                PrintWarning($"SkinsPerPage must be >= 1, got {_config.SkinsPerPage}. Falling back to 12.");
                _config.SkinsPerPage = 12;
            }

            SaveConfig();
        }

        protected override void SaveConfig() => Config.WriteObject(_config);

        // -------------------------------------------------------------------
        // Data
        // -------------------------------------------------------------------

        private class SkinSet
        {
            public string Name;
            public Dictionary<string, ulong> Items = new Dictionary<string, ulong>();
            public long CreatedAt;
            public long UpdatedAt;
        }

        private class PlayerData
        {
            public List<SkinSet> Sets = new List<SkinSet>();
            public string ActiveSet;
        }

        private class CatalogSkin
        {
            public ulong SkinId;
            public string Name;
            public string IconUrl;
            public bool Approved;
        }

        private class CatalogCategory
        {
            public string Shortname;
            public string Display;
            public List<CatalogSkin> Skins = new List<CatalogSkin>();
        }

        private class Catalog
        {
            public List<CatalogCategory> Categories = new List<CatalogCategory>();
        }

        private Catalog _catalog;

        private readonly Dictionary<ulong, PlayerData> _playerCache = new Dictionary<ulong, PlayerData>();

        private string DataRoot => Path.Combine(Interface.Oxide.DataDirectory, Name);
        private string DataPlayers => Path.Combine(DataRoot, "players");
        private string DataDesign => Path.Combine(DataRoot, "design");
        private string DataCatalog => Path.Combine(DataRoot, "skins.json");

        private void EnsureDataDirs()
        {
            Directory.CreateDirectory(DataRoot);
            Directory.CreateDirectory(DataPlayers);
            Directory.CreateDirectory(DataDesign);
        }

        private void LoadCatalog()
        {
            if (!File.Exists(DataCatalog))
            {
                _catalog = BuildDefaultCatalog();
                File.WriteAllText(DataCatalog, JsonConvert.SerializeObject(_catalog, Formatting.Indented));
                Puts($"Wrote default catalog to {DataCatalog} - edit and reload to customise.");
                return;
            }

            try
            {
                _catalog = JsonConvert.DeserializeObject<Catalog>(File.ReadAllText(DataCatalog)) ?? BuildDefaultCatalog();
            }
            catch (Exception e)
            {
                PrintError($"Failed to read {DataCatalog}: {e.Message}");
                _catalog = BuildDefaultCatalog();
            }
        }

        private static Catalog BuildDefaultCatalog()
        {
            // Small placeholder catalog. Server admins should edit
            // oxide/data/SkinMenu/skins.json (or let the python script
            // regenerate it from the Steam workshop).
            return new Catalog
            {
                Categories = new List<CatalogCategory>
                {
                    new CatalogCategory
                    {
                        Shortname = "rifle.ak",
                        Display = "AK-47",
                        Skins = new List<CatalogSkin>
                        {
                            new CatalogSkin { SkinId = 0, Name = "Default", Approved = true,
                                IconUrl = "https://rustlabs.com/img/items180/rifle.ak.png" },
                            new CatalogSkin { SkinId = 1308044604, Name = "Alien Red", Approved = true,
                                IconUrl = "https://steamcommunity.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGxq0kvSi2Ts1cbg6mDuhDPaqodSwBoX_LvD0w7AukrZ1OqAFcQKaJUNVD23wycDFw-zM5oOWh5sgRCcwoCxUjFSjyXX6lHL_BEbgs/240fx240f" }
                        }
                    },
                    new CatalogCategory
                    {
                        Shortname = "hoodie",
                        Display = "Hoodie",
                        Skins = new List<CatalogSkin>
                        {
                            new CatalogSkin { SkinId = 0, Name = "Default", Approved = true,
                                IconUrl = "https://rustlabs.com/img/items180/hoodie.png" }
                        }
                    },
                    new CatalogCategory
                    {
                        Shortname = "pants",
                        Display = "Pants",
                        Skins = new List<CatalogSkin>
                        {
                            new CatalogSkin { SkinId = 0, Name = "Default", Approved = true,
                                IconUrl = "https://rustlabs.com/img/items180/pants.png" }
                        }
                    }
                }
            };
        }

        private List<CatalogSkin> FilterSkins(CatalogCategory cat)
        {
            switch (_config.Mode)
            {
                case SkinMode.Approved:
                    return cat.Skins.Where(s => s.Approved).ToList();
                case SkinMode.Pending:
                    return cat.Skins.Where(s => !s.Approved).ToList();
                default:
                    return cat.Skins;
            }
        }

        private string PlayerFile(ulong id) => Path.Combine(DataPlayers, id + ".json");

        private PlayerData LoadPlayer(ulong id)
        {
            if (_playerCache.TryGetValue(id, out var cached)) return cached;

            var file = PlayerFile(id);
            PlayerData data;
            if (File.Exists(file))
            {
                try { data = JsonConvert.DeserializeObject<PlayerData>(File.ReadAllText(file)) ?? new PlayerData(); }
                catch (Exception e) { PrintError($"Bad player file for {id}: {e.Message}"); data = new PlayerData(); }
            }
            else
            {
                data = new PlayerData();
            }

            _playerCache[id] = data;
            return data;
        }

        private void SavePlayer(ulong id)
        {
            if (!_playerCache.TryGetValue(id, out var data)) return;
            File.WriteAllText(PlayerFile(id), JsonConvert.SerializeObject(data, Formatting.Indented));
        }

        // -------------------------------------------------------------------
        // Editor (per-player draft state while menu is open)
        // -------------------------------------------------------------------

        private class EditorState
        {
            public Dictionary<string, ulong> Selection = new Dictionary<string, ulong>();
            public int CategoryIndex;
            public int Page;
            public string EditingSetName;
        }

        // -------------------------------------------------------------------
        // Lifecycle
        // -------------------------------------------------------------------

        private void Init()
        {
            permission.RegisterPermission(PermUse, this);
            EnsureDataDirs();
            LoadCatalog();
        }

        private void OnServerInitialized()
        {
            if (!string.IsNullOrEmpty(_config.Command))
            {
                cmd.AddChatCommand(_config.Command, this, nameof(CmdMenu));
            }
            RegisterDesignImages();
        }

        private void Unload()
        {
            foreach (var p in BasePlayer.activePlayerList)
            {
                CloseAll(p);
            }
            foreach (var id in _playerCache.Keys.ToList()) SavePlayer(id);
        }

        private void OnPlayerRespawned(BasePlayer player)
        {
            if (!_config.ApplyDefaultOnRespawn || player == null) return;
            var data = LoadPlayer(player.userID);
            var set = data.Sets.FirstOrDefault(s =>
                string.Equals(s.Name, "default", StringComparison.OrdinalIgnoreCase));
            if (set != null) ApplySetToInventory(player, set);
        }

        // -------------------------------------------------------------------
        // ImageLibrary
        // -------------------------------------------------------------------

        private void RegisterDesignImages()
        {
            if (ImageLibrary == null)
            {
                PrintWarning("ImageLibrary is not loaded - skin icons and design assets will fall back to colour fills.");
                return;
            }

            // Skin icons.
            foreach (var cat in _catalog.Categories)
            {
                foreach (var skin in cat.Skins)
                {
                    if (string.IsNullOrEmpty(skin.IconUrl)) continue;
                    var key = SkinImageKey(cat.Shortname, skin.SkinId);
                    ImageLibrary.Call("AddImage", skin.IconUrl, key, (ulong)0);
                }
            }

            // Design assets (from data/SkinMenu/design/, registered as
            // file:// URLs so ImageLibrary picks them up from disk).
            RegisterDesignFile("bg", _config.Design.Background);
            RegisterDesignFile("slot", _config.Design.SlotFrame);
            RegisterDesignFile("slot_active", _config.Design.SlotFrameActive);
            RegisterDesignFile("button", _config.Design.Button);
            RegisterDesignFile("button_hl", _config.Design.ButtonHighlight);
        }

        private void RegisterDesignFile(string key, string file)
        {
            if (string.IsNullOrEmpty(file)) return;
            var full = Path.Combine(DataDesign, file);
            if (!File.Exists(full))
            {
                PrintWarning($"Design file missing: {full} - run design_generator.py to create it.");
                return;
            }
            ImageLibrary?.Call("AddImage", "file:///" + full.Replace('\\', '/'), "design." + key, (ulong)0);
        }

        private static string SkinImageKey(string shortname, ulong skinId) => $"skin.{shortname}.{skinId}";

        private string GetImage(string key)
        {
            if (ImageLibrary == null) return null;
            return ImageLibrary.Call<string>("GetImage", key, (ulong)0, false);
        }

        // -------------------------------------------------------------------
        // Commands
        // -------------------------------------------------------------------

        private void CmdMenu(BasePlayer player, string command, string[] args)
        {
            if (!permission.UserHasPermission(player.UserIDString, PermUse))
            {
                player.ChatMessage("You don't have permission to use the skin menu.");
                return;
            }

            OpenMain(player);
        }

        [ConsoleCommand("skinmenu.ui")]
        private void CmdUi(ConsoleSystem.Arg arg)
        {
            var player = arg?.Player();
            if (player == null || !arg.HasArgs(1)) return;
            if (!permission.UserHasPermission(player.UserIDString, PermUse)) return;

            var action = arg.GetString(0);
            switch (action)
            {
                case "close":
                    CloseAll(player);
                    break;

                case "category":
                    HandleCategory(player, arg.GetInt(1, 0));
                    break;

                case "page":
                    HandlePage(player, arg.GetInt(1, 0));
                    break;

                case "pick":
                    HandlePick(player, arg.GetString(1), arg.GetULong(2, 0));
                    break;

                case "create":
                    PromptSetName(player, "Create new set", "create.confirm");
                    break;

                case "create.confirm":
                    HandleCreate(player, JoinFrom(arg, 1));
                    break;

                case "save":
                    HandleSave(player);
                    break;

                case "apply":
                    HandleApply(player);
                    break;

                case "sets":
                    OpenSetList(player);
                    break;

                case "set.load":
                    HandleLoadSet(player, JoinFrom(arg, 1));
                    break;

                case "set.enable":
                    HandleEnableSet(player, JoinFrom(arg, 1));
                    break;

                case "set.delete":
                    HandleDeleteSet(player, JoinFrom(arg, 1));
                    break;

                case "prompt.close":
                    CuiHelper.DestroyUi(player, PromptPanel);
                    break;
            }
        }

        private static string JoinFrom(ConsoleSystem.Arg arg, int start)
        {
            if (arg.Args == null || arg.Args.Length <= start) return string.Empty;
            return string.Join(" ", arg.Args.Skip(start));
        }

        // -------------------------------------------------------------------
        // Menu handlers
        // -------------------------------------------------------------------

        private EditorState Editor(BasePlayer p)
        {
            if (!_editors.TryGetValue(p.userID, out var st))
            {
                st = new EditorState();
                // Seed from player's active set, if any.
                var data = LoadPlayer(p.userID);
                var active = data.Sets.FirstOrDefault(s => s.Name == data.ActiveSet);
                if (active != null)
                {
                    foreach (var kv in active.Items) st.Selection[kv.Key] = kv.Value;
                    st.EditingSetName = active.Name;
                }
                _editors[p.userID] = st;
            }
            return st;
        }

        private void HandleCategory(BasePlayer p, int idx)
        {
            var st = Editor(p);
            st.CategoryIndex = Math.Max(0, Math.Min(idx, _catalog.Categories.Count - 1));
            st.Page = 0;
            OpenMain(p);
        }

        private void HandlePage(BasePlayer p, int delta)
        {
            var st = Editor(p);
            var skins = FilterSkins(_catalog.Categories[st.CategoryIndex]);
            var maxPage = Math.Max(0, (skins.Count - 1) / _config.SkinsPerPage);
            st.Page = Mathf.Clamp(st.Page + delta, 0, maxPage);
            OpenMain(p);
        }

        private void HandlePick(BasePlayer p, string shortname, ulong skinId)
        {
            var st = Editor(p);
            st.Selection[shortname] = skinId;
            OpenMain(p);
        }

        private void HandleCreate(BasePlayer p, string name)
        {
            name = (name ?? string.Empty).Trim();
            if (name.Length == 0) { p.ChatMessage("Set name cannot be empty."); return; }

            var data = LoadPlayer(p.userID);
            if (data.Sets.Any(s => string.Equals(s.Name, name, StringComparison.OrdinalIgnoreCase)))
            {
                p.ChatMessage($"You already have a set named '{name}'.");
                return;
            }

            var st = Editor(p);
            var now = DateTimeOffset.UtcNow.ToUnixTimeSeconds();
            data.Sets.Add(new SkinSet
            {
                Name = name,
                Items = new Dictionary<string, ulong>(st.Selection),
                CreatedAt = now,
                UpdatedAt = now,
            });
            data.ActiveSet = name;
            st.EditingSetName = name;
            SavePlayer(p.userID);

            CuiHelper.DestroyUi(p, PromptPanel);
            p.ChatMessage($"Created skin set '{name}'.");
            OpenMain(p);
        }

        private void HandleSave(BasePlayer p)
        {
            var st = Editor(p);
            if (string.IsNullOrEmpty(st.EditingSetName))
            {
                p.ChatMessage("No active set - press 'Create set' first.");
                return;
            }

            var data = LoadPlayer(p.userID);
            var set = data.Sets.FirstOrDefault(s =>
                string.Equals(s.Name, st.EditingSetName, StringComparison.OrdinalIgnoreCase));
            if (set == null)
            {
                p.ChatMessage($"Set '{st.EditingSetName}' no longer exists.");
                return;
            }

            set.Items = new Dictionary<string, ulong>(st.Selection);
            set.UpdatedAt = DateTimeOffset.UtcNow.ToUnixTimeSeconds();
            SavePlayer(p.userID);
            p.ChatMessage($"Saved skin set '{set.Name}'.");
        }

        private void HandleApply(BasePlayer p)
        {
            var st = Editor(p);
            var temp = new SkinSet { Name = st.EditingSetName ?? "<draft>", Items = st.Selection };
            ApplySetToInventory(p, temp);
            p.ChatMessage("Applied current selection to your inventory items.");
        }

        private void HandleLoadSet(BasePlayer p, string name)
        {
            var data = LoadPlayer(p.userID);
            var set = data.Sets.FirstOrDefault(s =>
                string.Equals(s.Name, name, StringComparison.OrdinalIgnoreCase));
            if (set == null) return;

            var st = Editor(p);
            st.Selection = new Dictionary<string, ulong>(set.Items);
            st.EditingSetName = set.Name;
            data.ActiveSet = set.Name;
            SavePlayer(p.userID);
            OpenMain(p);
        }

        private void HandleEnableSet(BasePlayer p, string name)
        {
            var data = LoadPlayer(p.userID);
            var set = data.Sets.FirstOrDefault(s =>
                string.Equals(s.Name, name, StringComparison.OrdinalIgnoreCase));
            if (set == null) return;
            data.ActiveSet = set.Name;
            SavePlayer(p.userID);
            ApplySetToInventory(p, set);
            p.ChatMessage($"Enabled set '{set.Name}'.");
        }

        private void HandleDeleteSet(BasePlayer p, string name)
        {
            var data = LoadPlayer(p.userID);
            var removed = data.Sets.RemoveAll(s =>
                string.Equals(s.Name, name, StringComparison.OrdinalIgnoreCase));
            if (removed > 0)
            {
                if (string.Equals(data.ActiveSet, name, StringComparison.OrdinalIgnoreCase))
                    data.ActiveSet = null;
                SavePlayer(p.userID);
                p.ChatMessage($"Deleted set '{name}'.");
            }
            OpenSetList(p);
        }

        // -------------------------------------------------------------------
        // Inventory apply
        // -------------------------------------------------------------------

        private void ApplySetToInventory(BasePlayer p, SkinSet set)
        {
            if (p == null || p.inventory == null || set == null) return;

            foreach (var container in new[] { p.inventory.containerMain, p.inventory.containerBelt, p.inventory.containerWear })
            {
                if (container == null) continue;
                foreach (var item in container.itemList)
                {
                    if (item == null || item.info == null) continue;
                    if (!set.Items.TryGetValue(item.info.shortname, out var skin)) continue;

                    item.skin = skin;
                    item.MarkDirty();
                    var held = item.GetHeldEntity();
                    if (held != null)
                    {
                        held.skinID = skin;
                        held.SendNetworkUpdate();
                    }
                }
            }
        }

        // -------------------------------------------------------------------
        // UI
        // -------------------------------------------------------------------

        private void CloseAll(BasePlayer p)
        {
            CuiHelper.DestroyUi(p, MainPanel);
            CuiHelper.DestroyUi(p, ListPanel);
            CuiHelper.DestroyUi(p, PromptPanel);
            _editors.Remove(p.userID);
        }

        private void OpenMain(BasePlayer p)
        {
            CuiHelper.DestroyUi(p, MainPanel);

            var st = Editor(p);
            if (_catalog.Categories.Count == 0)
            {
                p.ChatMessage("Skin catalog is empty - edit data/SkinMenu/skins.json on the server.");
                return;
            }

            st.CategoryIndex = Mathf.Clamp(st.CategoryIndex, 0, _catalog.Categories.Count - 1);
            var category = _catalog.Categories[st.CategoryIndex];
            var skins = FilterSkins(category);
            var totalPages = Math.Max(1, (int)Math.Ceiling(skins.Count / (double)_config.SkinsPerPage));
            st.Page = Mathf.Clamp(st.Page, 0, totalPages - 1);

            var elements = new CuiElementContainer();
            BuildBackground(elements);
            BuildHeader(elements, category, st.Page, totalPages);
            BuildCategoryTabs(elements, st.CategoryIndex);
            BuildSkinGrid(elements, category, skins, st);
            BuildActionButtons(elements, st);
            BuildFooter(elements);

            CuiHelper.AddUi(p, elements);
        }

        private void BuildBackground(CuiElementContainer elements)
        {
            elements.Add(new CuiPanel
            {
                Image = { Color = "0 0 0 0.85" },
                RectTransform = { AnchorMin = "0 0", AnchorMax = "1 1" },
                CursorEnabled = true,
            }, "Overlay", MainPanel);

            var bg = GetImage("design.bg");
            if (!string.IsNullOrEmpty(bg))
            {
                elements.Add(new CuiElement
                {
                    Parent = MainPanel,
                    Name = MainPanel + ".bg",
                    Components =
                    {
                        new CuiRawImageComponent { Png = bg },
                        new CuiRectTransformComponent { AnchorMin = "0.18 0.08", AnchorMax = "0.82 0.92" }
                    }
                });
            }
            else
            {
                elements.Add(new CuiPanel
                {
                    Image = { Color = "0.12 0.13 0.15 0.95" },
                    RectTransform = { AnchorMin = "0.18 0.08", AnchorMax = "0.82 0.92" },
                }, MainPanel, MainPanel + ".bg");
            }
        }

        private void BuildHeader(CuiElementContainer elements, CatalogCategory cat, int page, int totalPages)
        {
            elements.Add(new CuiLabel
            {
                Text = { Text = $"<b>SKIN MENU</b>  -  {cat.Display}  ({page + 1}/{totalPages})",
                         FontSize = 18, Align = TextAnchor.MiddleLeft, Color = "1 1 1 1" },
                RectTransform = { AnchorMin = "0.04 0.9", AnchorMax = "0.7 0.97" },
            }, MainPanel + ".bg");

            // Close.
            elements.Add(new CuiButton
            {
                Button = { Color = "0.6 0.1 0.1 0.9", Command = "skinmenu.ui close" },
                Text = { Text = "X", FontSize = 16, Align = TextAnchor.MiddleCenter, Color = "1 1 1 1" },
                RectTransform = { AnchorMin = "0.94 0.92", AnchorMax = "0.985 0.98" },
            }, MainPanel + ".bg");
        }

        private void BuildCategoryTabs(CuiElementContainer elements, int activeIndex)
        {
            const float top = 0.84f;
            const float bot = 0.89f;
            const float left = 0.04f;
            const float right = 0.96f;
            var count = _catalog.Categories.Count;
            if (count == 0) return;

            var width = (right - left) / count;
            for (var i = 0; i < count; i++)
            {
                var min = left + i * width + 0.005f;
                var max = left + (i + 1) * width - 0.005f;
                var active = i == activeIndex;
                elements.Add(new CuiButton
                {
                    Button = { Color = active ? "0.2 0.55 0.85 0.9" : "0.2 0.2 0.22 0.85",
                               Command = $"skinmenu.ui category {i}" },
                    Text = { Text = _catalog.Categories[i].Display, FontSize = 12,
                             Align = TextAnchor.MiddleCenter, Color = "1 1 1 1" },
                    RectTransform = { AnchorMin = $"{min} {top}", AnchorMax = $"{max} {bot}" },
                }, MainPanel + ".bg");
            }
        }

        private void BuildSkinGrid(CuiElementContainer elements, CatalogCategory cat,
                                   List<CatalogSkin> skins, EditorState st)
        {
            const float top = 0.78f;
            const float bot = 0.30f;
            const float left = 0.06f;
            const float right = 0.94f;
            const int cols = 4;
            var rows = Math.Max(1, _config.SkinsPerPage / cols);

            var slotW = (right - left) / cols;
            var slotH = (top - bot) / rows;
            var startIdx = st.Page * _config.SkinsPerPage;

            var selectedSkin = st.Selection.TryGetValue(cat.Shortname, out var s) ? s : 0UL;

            for (var i = 0; i < _config.SkinsPerPage; i++)
            {
                var idx = startIdx + i;
                if (idx >= skins.Count) break;
                var skin = skins[idx];
                var col = i % cols;
                var row = i / cols;
                var xMin = left + col * slotW + 0.01f;
                var xMax = left + (col + 1) * slotW - 0.01f;
                var yMax = top - row * slotH - 0.01f;
                var yMin = top - (row + 1) * slotH + 0.01f;
                var isActive = skin.SkinId == selectedSkin;

                var slotName = $"{MainPanel}.slot.{i}";

                // Slot frame.
                var frame = GetImage(isActive ? "design.slot_active" : "design.slot");
                if (!string.IsNullOrEmpty(frame))
                {
                    elements.Add(new CuiElement
                    {
                        Parent = MainPanel + ".bg",
                        Name = slotName,
                        Components =
                        {
                            new CuiRawImageComponent { Png = frame },
                            new CuiRectTransformComponent { AnchorMin = $"{xMin} {yMin}", AnchorMax = $"{xMax} {yMax}" }
                        }
                    });
                }
                else
                {
                    elements.Add(new CuiPanel
                    {
                        Image = { Color = isActive ? "0.2 0.55 0.85 0.6" : "0.18 0.18 0.2 0.85" },
                        RectTransform = { AnchorMin = $"{xMin} {yMin}", AnchorMax = $"{xMax} {yMax}" },
                    }, MainPanel + ".bg", slotName);
                }

                // Skin icon.
                var iconKey = SkinImageKey(cat.Shortname, skin.SkinId);
                var iconImg = GetImage(iconKey);
                if (!string.IsNullOrEmpty(iconImg))
                {
                    elements.Add(new CuiElement
                    {
                        Parent = slotName,
                        Components =
                        {
                            new CuiRawImageComponent { Png = iconImg },
                            new CuiRectTransformComponent { AnchorMin = "0.1 0.25", AnchorMax = "0.9 0.95" }
                        }
                    });
                }

                // Label.
                elements.Add(new CuiLabel
                {
                    Text = { Text = skin.Name ?? skin.SkinId.ToString(),
                             FontSize = 10, Align = TextAnchor.MiddleCenter, Color = "1 1 1 1" },
                    RectTransform = { AnchorMin = "0 0.02", AnchorMax = "1 0.2" },
                }, slotName);

                // Invisible button covering the slot.
                elements.Add(new CuiButton
                {
                    Button = { Color = "0 0 0 0", Command = $"skinmenu.ui pick {cat.Shortname} {skin.SkinId}" },
                    Text = { Text = string.Empty },
                    RectTransform = { AnchorMin = "0 0", AnchorMax = "1 1" },
                }, slotName);
            }

            // Pager arrows.
            elements.Add(new CuiButton
            {
                Button = { Color = "0.2 0.2 0.22 0.85", Command = "skinmenu.ui page -1" },
                Text = { Text = "<", FontSize = 18, Align = TextAnchor.MiddleCenter, Color = "1 1 1 1" },
                RectTransform = { AnchorMin = "0.02 0.5", AnchorMax = "0.055 0.58" },
            }, MainPanel + ".bg");

            elements.Add(new CuiButton
            {
                Button = { Color = "0.2 0.2 0.22 0.85", Command = "skinmenu.ui page 1" },
                Text = { Text = ">", FontSize = 18, Align = TextAnchor.MiddleCenter, Color = "1 1 1 1" },
                RectTransform = { AnchorMin = "0.945 0.5", AnchorMax = "0.98 0.58" },
            }, MainPanel + ".bg");
        }

        private void BuildActionButtons(CuiElementContainer elements, EditorState st)
        {
            const float top = 0.26f;
            const float bot = 0.18f;
            var labels = new[] { "Create set", "Save set", "Enable set" };
            var cmds = new[] { "skinmenu.ui create", "skinmenu.ui save", "skinmenu.ui apply" };
            const float left = 0.1f;
            const float right = 0.9f;
            var width = (right - left) / labels.Length;

            for (var i = 0; i < labels.Length; i++)
            {
                var min = left + i * width + 0.01f;
                var max = left + (i + 1) * width - 0.01f;
                elements.Add(new CuiButton
                {
                    Button = { Color = "0.2 0.55 0.85 0.9", Command = cmds[i] },
                    Text = { Text = labels[i], FontSize = 14, Align = TextAnchor.MiddleCenter, Color = "1 1 1 1" },
                    RectTransform = { AnchorMin = $"{min} {bot}", AnchorMax = $"{max} {top}" },
                }, MainPanel + ".bg");
            }

            var active = string.IsNullOrEmpty(st.EditingSetName) ? "<i>(no active set)</i>" : $"<b>{st.EditingSetName}</b>";
            elements.Add(new CuiLabel
            {
                Text = { Text = "Active set: " + active, FontSize = 12,
                         Align = TextAnchor.MiddleCenter, Color = "0.85 0.85 0.85 1" },
                RectTransform = { AnchorMin = "0.1 0.13", AnchorMax = "0.9 0.17" },
            }, MainPanel + ".bg");
        }

        private void BuildFooter(CuiElementContainer elements)
        {
            elements.Add(new CuiButton
            {
                Button = { Color = "0.25 0.25 0.28 0.95", Command = "skinmenu.ui sets" },
                Text = { Text = "All sets", FontSize = 14, Align = TextAnchor.MiddleCenter, Color = "1 1 1 1" },
                RectTransform = { AnchorMin = "0.35 0.04", AnchorMax = "0.65 0.11" },
            }, MainPanel + ".bg");
        }

        // ---- Sets list ----

        private void OpenSetList(BasePlayer p)
        {
            CuiHelper.DestroyUi(p, ListPanel);

            var data = LoadPlayer(p.userID);
            var elements = new CuiElementContainer();

            elements.Add(new CuiPanel
            {
                Image = { Color = "0.08 0.08 0.1 0.97" },
                RectTransform = { AnchorMin = "0.3 0.2", AnchorMax = "0.7 0.85" },
                CursorEnabled = true,
            }, "Overlay", ListPanel);

            elements.Add(new CuiLabel
            {
                Text = { Text = "<b>YOUR SKIN SETS</b>", FontSize = 16,
                         Align = TextAnchor.MiddleCenter, Color = "1 1 1 1" },
                RectTransform = { AnchorMin = "0 0.92", AnchorMax = "1 0.99" },
            }, ListPanel);

            elements.Add(new CuiButton
            {
                Button = { Color = "0.6 0.1 0.1 0.9", Command = "skinmenu.ui close" },
                Text = { Text = "X", FontSize = 14, Align = TextAnchor.MiddleCenter, Color = "1 1 1 1" },
                RectTransform = { AnchorMin = "0.93 0.93", AnchorMax = "0.99 0.99" },
            }, ListPanel);

            if (data.Sets.Count == 0)
            {
                elements.Add(new CuiLabel
                {
                    Text = { Text = "You have no sets yet. Press <b>Create set</b> in the main menu.",
                             FontSize = 12, Align = TextAnchor.MiddleCenter, Color = "0.85 0.85 0.85 1" },
                    RectTransform = { AnchorMin = "0.05 0.5", AnchorMax = "0.95 0.6" },
                }, ListPanel);
            }
            else
            {
                const float top = 0.88f;
                const float rowH = 0.08f;
                for (var i = 0; i < data.Sets.Count && i < 9; i++)
                {
                    var set = data.Sets[i];
                    var yMax = top - i * rowH;
                    var yMin = yMax - rowH + 0.005f;

                    elements.Add(new CuiPanel
                    {
                        Image = { Color = "0.15 0.15 0.18 0.95" },
                        RectTransform = { AnchorMin = $"0.05 {yMin}", AnchorMax = $"0.95 {yMax}" },
                    }, ListPanel, $"{ListPanel}.row.{i}");

                    elements.Add(new CuiLabel
                    {
                        Text = { Text = $"{set.Name}  <color=#888>({set.Items.Count} items)</color>",
                                 FontSize = 13, Align = TextAnchor.MiddleLeft, Color = "1 1 1 1" },
                        RectTransform = { AnchorMin = "0.03 0", AnchorMax = "0.5 1" },
                    }, $"{ListPanel}.row.{i}");

                    elements.Add(new CuiButton
                    {
                        Button = { Color = "0.2 0.55 0.85 0.9",
                                   Command = $"skinmenu.ui set.load {set.Name}" },
                        Text = { Text = "Load", FontSize = 11, Align = TextAnchor.MiddleCenter, Color = "1 1 1 1" },
                        RectTransform = { AnchorMin = "0.52 0.15", AnchorMax = "0.66 0.85" },
                    }, $"{ListPanel}.row.{i}");

                    elements.Add(new CuiButton
                    {
                        Button = { Color = "0.2 0.6 0.3 0.9",
                                   Command = $"skinmenu.ui set.enable {set.Name}" },
                        Text = { Text = "Enable", FontSize = 11, Align = TextAnchor.MiddleCenter, Color = "1 1 1 1" },
                        RectTransform = { AnchorMin = "0.68 0.15", AnchorMax = "0.82 0.85" },
                    }, $"{ListPanel}.row.{i}");

                    elements.Add(new CuiButton
                    {
                        Button = { Color = "0.6 0.2 0.2 0.9",
                                   Command = $"skinmenu.ui set.delete {set.Name}" },
                        Text = { Text = "Delete", FontSize = 11, Align = TextAnchor.MiddleCenter, Color = "1 1 1 1" },
                        RectTransform = { AnchorMin = "0.84 0.15", AnchorMax = "0.97 0.85" },
                    }, $"{ListPanel}.row.{i}");
                }
            }

            CuiHelper.AddUi(p, elements);
        }

        // ---- Prompt ----

        private void PromptSetName(BasePlayer p, string title, string confirmAction)
        {
            CuiHelper.DestroyUi(p, PromptPanel);
            var elements = new CuiElementContainer();

            elements.Add(new CuiPanel
            {
                Image = { Color = "0 0 0 0.6" },
                RectTransform = { AnchorMin = "0 0", AnchorMax = "1 1" },
                CursorEnabled = true,
            }, "Overlay", PromptPanel);

            elements.Add(new CuiPanel
            {
                Image = { Color = "0.12 0.13 0.15 0.98" },
                RectTransform = { AnchorMin = "0.38 0.42", AnchorMax = "0.62 0.58" },
            }, PromptPanel, PromptPanel + ".inner");

            elements.Add(new CuiLabel
            {
                Text = { Text = title, FontSize = 14, Align = TextAnchor.MiddleCenter, Color = "1 1 1 1" },
                RectTransform = { AnchorMin = "0 0.78", AnchorMax = "1 0.98" },
            }, PromptPanel + ".inner");

            elements.Add(new CuiElement
            {
                Parent = PromptPanel + ".inner",
                Components =
                {
                    new CuiInputFieldComponent
                    {
                        FontSize = 14, Align = TextAnchor.MiddleCenter, Color = "1 1 1 1",
                        CharsLimit = 24,
                        Command = "skinmenu.ui " + confirmAction + " ",
                        IsPassword = false, NeedsKeyboard = true,
                    },
                    new CuiImageComponent { Color = "0.2 0.2 0.25 0.95" },
                    new CuiRectTransformComponent { AnchorMin = "0.1 0.4", AnchorMax = "0.9 0.7" }
                }
            });

            elements.Add(new CuiButton
            {
                Button = { Color = "0.6 0.2 0.2 0.9", Command = "skinmenu.ui prompt.close" },
                Text = { Text = "Cancel", FontSize = 11, Align = TextAnchor.MiddleCenter, Color = "1 1 1 1" },
                RectTransform = { AnchorMin = "0.55 0.1", AnchorMax = "0.9 0.32" },
            }, PromptPanel + ".inner");

            elements.Add(new CuiLabel
            {
                Text = { Text = "<size=10>Type a name and press Enter</size>",
                         FontSize = 10, Align = TextAnchor.MiddleLeft, Color = "0.7 0.7 0.7 1" },
                RectTransform = { AnchorMin = "0.1 0.1", AnchorMax = "0.55 0.32" },
            }, PromptPanel + ".inner");

            CuiHelper.AddUi(p, elements);
        }
    }
}
