// Requires: ImageLibrary
//
// SkinMenu - skin sets menu for Rust (uMod / Oxide).
//
// Players open a CUI menu that lets them pick a skin per item category,
// save the selection as a named "set", and apply any saved set to their
// inventory. The menu background and frame PNGs are generated by the
// companion Python / Pillow script (design_generator.py) into the
// `oxide/data/SkinMenu/design/` folder. They are read straight from
// disk and uploaded to the server's FileStorage at plugin load
// (ImageLibrary is only used for the skin / category icon URLs).
//
// Skin catalog modes (configurable):
//   "All"      - every skin in the catalog (includes pending workshop
//                items - can be risky on EAC-strict servers).
//   "Approved" - only skins that Facepunch has approved into the game
//                (safe).
//   "Pending"  - only skins that are still pending approval (use at
//                your own risk).

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Oxide.Core;
using Oxide.Core.Plugins;
using Oxide.Game.Rust.Cui;
using UnityEngine;

namespace Oxide.Plugins
{
    [Info("SkinMenu", "Devin", "1.1.0")]
    [Description("Per-player skin set menu with CUI design generated via Python + Pillow.")]
    public class SkinMenu : RustPlugin
    {
        [PluginReference] private Plugin ImageLibrary;

        private const string MainPanel = "skinmenu.main";
        private const string FramePanel = "skinmenu.frame";
        private const string ListPanel = "skinmenu.list";
        private const string PromptPanel = "skinmenu.prompt";

        private const string PermUse = "skinmenu.use";

        // Inner frame occupies 60% width x 80% height of the screen.
        // Within that frame, 1 unit of x covers 0.6 * 16 = 9.6 visual
        // units and 1 unit of y covers 0.8 * 9 = 7.2 visual units, so
        // to draw a SQUARE inside the frame: height_norm = width_norm
        // * (9.6 / 7.2) = width_norm * 4 / 3.
        private const float FrameSquareYPerX = 9.6f / 7.2f;

        private readonly Dictionary<ulong, EditorState> _editors = new Dictionary<ulong, EditorState>();
        private readonly Dictionary<string, string> _designPng = new Dictionary<string, string>();

        // -------------------------------------------------------------------
        // Config
        // -------------------------------------------------------------------

        public enum SkinMode { All, Approved, Pending }

        private class PluginConfig
        {
            [JsonProperty("Command to open the menu")]
            public string Command = "skinmenu";

            [JsonProperty("Skin catalog mode (All / Approved / Pending)")]
            [JsonConverter(typeof(StringEnumConverter))]
            public SkinMode Mode = SkinMode.Approved;

            [JsonProperty("How many skins per page in the grid")]
            public int SkinsPerPage = 8;

            [JsonProperty("Auto-apply set on respawn if a set is named 'default'")]
            public bool ApplyDefaultOnRespawn = true;

            [JsonProperty("Design image file names (placed in oxide/data/SkinMenu/design/)")]
            public DesignImages Design = new DesignImages();

            public class DesignImages
            {
                [JsonProperty("Main panel background")]
                public string Background = "bg.png";

                [JsonProperty("Skin slot frame")]
                public string SlotFrame = "slot.png";

                [JsonProperty("Selected skin slot frame")]
                public string SlotFrameActive = "slot_active.png";

                [JsonProperty("Generic button background")]
                public string Button = "button.png";

                [JsonProperty("Highlighted button background")]
                public string ButtonHighlight = "button_hl.png";
            }
        }

        private PluginConfig _config;

        protected override void LoadDefaultConfig() => _config = new PluginConfig();

        protected override void LoadConfig()
        {
            base.LoadConfig();
            try
            {
                _config = Config.ReadObject<PluginConfig>() ?? new PluginConfig();
            }
            catch (Exception e)
            {
                PrintError($"Config file is corrupted, resetting to defaults: {e.Message}");
                LoadDefaultConfig();
            }

            if (_config.SkinsPerPage < 1)
            {
                PrintWarning($"SkinsPerPage must be >= 1, got {_config.SkinsPerPage}. Falling back to 8.");
                _config.SkinsPerPage = 8;
            }

            SaveConfig();
        }

        protected override void SaveConfig() => Config.WriteObject(_config);

        // -------------------------------------------------------------------
        // Data
        // -------------------------------------------------------------------

        private class SkinSet
        {
            public string Name;
            public Dictionary<string, ulong> Items = new Dictionary<string, ulong>();
            public long CreatedAt;
            public long UpdatedAt;
        }

        private class PlayerData
        {
            public List<SkinSet> Sets = new List<SkinSet>();
            public string ActiveSet;
        }

        private class CatalogSkin
        {
            public ulong SkinId;
            public string Name;
            public string IconUrl;
            public bool Approved;
        }

        private class CatalogCategory
        {
            public string Shortname;
            public string Display;
            public string Icon;
            public List<CatalogSkin> Skins = new List<CatalogSkin>();
        }

        private class Catalog
        {
            public List<CatalogCategory> Categories = new List<CatalogCategory>();
        }

        private Catalog _catalog;

        private readonly Dictionary<ulong, PlayerData> _playerCache = new Dictionary<ulong, PlayerData>();

        private string DataRoot => Path.Combine(Interface.Oxide.DataDirectory, Name);
        private string DataPlayers => Path.Combine(DataRoot, "players");
        private string DataDesign => Path.Combine(DataRoot, "design");
        private string DataCatalog => Path.Combine(DataRoot, "skins.json");

        private void EnsureDataDirs()
        {
            Directory.CreateDirectory(DataRoot);
            Directory.CreateDirectory(DataPlayers);
            Directory.CreateDirectory(DataDesign);
        }

        private void LoadCatalog()
        {
            if (!File.Exists(DataCatalog))
            {
                _catalog = BuildDefaultCatalog();
                File.WriteAllText(DataCatalog, JsonConvert.SerializeObject(_catalog, Formatting.Indented));
                Puts($"Wrote default catalog to {DataCatalog} - edit and reload to customise.");
                return;
            }

            try
            {
                _catalog = JsonConvert.DeserializeObject<Catalog>(File.ReadAllText(DataCatalog)) ?? BuildDefaultCatalog();
            }
            catch (Exception e)
            {
                PrintError($"Failed to read {DataCatalog}: {e.Message}");
                _catalog = BuildDefaultCatalog();
            }
        }

        private static Catalog BuildDefaultCatalog()
        {
            return new Catalog
            {
                Categories = new List<CatalogCategory>
                {
                    new CatalogCategory
                    {
                        Shortname = "rifle.ak",
                        Display = "AK-47",
                        Icon = "https://rustlabs.com/img/items180/rifle.ak.png",
                        Skins = new List<CatalogSkin>
                        {
                            new CatalogSkin { SkinId = 0, Name = "Default", Approved = true,
                                IconUrl = "https://rustlabs.com/img/items180/rifle.ak.png" },
                            new CatalogSkin { SkinId = 1308044604, Name = "Alien Red", Approved = true,
                                IconUrl = "https://steamcommunity.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGxq0kvSi2Ts1cbg6mDuhDPaqodSwBoX_LvD0w7AukrZ1OqAFcQKaJUNVD23wycDFw-zM5oOWh5sgRCcwoCxUjFSjyXX6lHL_BEbgs/240fx240f" }
                        }
                    },
                    new CatalogCategory
                    {
                        Shortname = "hoodie",
                        Display = "Hoodie",
                        Icon = "https://rustlabs.com/img/items180/hoodie.png",
                        Skins = new List<CatalogSkin>
                        {
                            new CatalogSkin { SkinId = 0, Name = "Default", Approved = true,
                                IconUrl = "https://rustlabs.com/img/items180/hoodie.png" }
                        }
                    },
                    new CatalogCategory
                    {
                        Shortname = "pants",
                        Display = "Pants",
                        Icon = "https://rustlabs.com/img/items180/pants.png",
                        Skins = new List<CatalogSkin>
                        {
                            new CatalogSkin { SkinId = 0, Name = "Default", Approved = true,
                                IconUrl = "https://rustlabs.com/img/items180/pants.png" }
                        }
                    }
                }
            };
        }

        private List<CatalogSkin> FilterSkins(CatalogCategory cat)
        {
            switch (_config.Mode)
            {
                case SkinMode.Approved:
                    return cat.Skins.Where(s => s.Approved).ToList();
                case SkinMode.Pending:
                    return cat.Skins.Where(s => !s.Approved).ToList();
                default:
                    return cat.Skins;
            }
        }

        private string PlayerFile(ulong id) => Path.Combine(DataPlayers, id + ".json");

        private PlayerData LoadPlayer(ulong id)
        {
            if (_playerCache.TryGetValue(id, out var cached)) return cached;

            var file = PlayerFile(id);
            PlayerData data;
            if (File.Exists(file))
            {
                try { data = JsonConvert.DeserializeObject<PlayerData>(File.ReadAllText(file)) ?? new PlayerData(); }
                catch (Exception e) { PrintError($"Bad player file for {id}: {e.Message}"); data = new PlayerData(); }
            }
            else
            {
                data = new PlayerData();
            }

            _playerCache[id] = data;
            return data;
        }

        private void SavePlayer(ulong id)
        {
            if (!_playerCache.TryGetValue(id, out var data)) return;
            File.WriteAllText(PlayerFile(id), JsonConvert.SerializeObject(data, Formatting.Indented));
        }

        // -------------------------------------------------------------------
        // Editor (per-player draft state while menu is open)
        // -------------------------------------------------------------------

        private class EditorState
        {
            public Dictionary<string, ulong> Selection = new Dictionary<string, ulong>();
            public int CategoryIndex;
            public int Page;
            public string EditingSetName;
        }

        // -------------------------------------------------------------------
        // Lifecycle
        // -------------------------------------------------------------------

        private void Init()
        {
            permission.RegisterPermission(PermUse, this);
            EnsureDataDirs();
            LoadCatalog();
        }

        private void OnServerInitialized()
        {
            if (!string.IsNullOrEmpty(_config.Command))
            {
                cmd.AddChatCommand(_config.Command, this, nameof(CmdMenu));
            }
            LoadDesignAssets();
            RegisterRemoteImages();
        }

        private void Unload()
        {
            foreach (var p in BasePlayer.activePlayerList)
            {
                CloseAll(p);
            }
            foreach (var id in _playerCache.Keys.ToList()) SavePlayer(id);
        }

        private void OnPlayerRespawned(BasePlayer player)
        {
            if (!_config.ApplyDefaultOnRespawn || player == null) return;
            var data = LoadPlayer(player.userID);
            var set = data.Sets.FirstOrDefault(s =>
                string.Equals(s.Name, "default", StringComparison.OrdinalIgnoreCase));
            if (set != null) ApplySetToInventory(player, set);
        }

        // -------------------------------------------------------------------
        // Image loading
        // -------------------------------------------------------------------

        // Local PNG files are uploaded straight to FileStorage on the
        // server entity - this is the same path that vanilla CUI uses
        // and avoids "RPC Error in AddUI" caused by stale / wrong CRCs
        // coming back from ImageLibrary's file:// path.
        private void LoadDesignAssets()
        {
            _designPng.Clear();

            var server = FileStorage.server;
            if (server == null)
            {
                PrintWarning("FileStorage.server is null - design assets disabled.");
                return;
            }

            var entity = CommunityEntity.ServerInstance;
            if (entity == null || entity.net == null)
            {
                PrintWarning("CommunityEntity.ServerInstance is unavailable - design assets disabled.");
                return;
            }

            LoadDesignAsset("bg", _config.Design.Background, server, entity);
            LoadDesignAsset("slot", _config.Design.SlotFrame, server, entity);
            LoadDesignAsset("slot_active", _config.Design.SlotFrameActive, server, entity);
            LoadDesignAsset("button", _config.Design.Button, server, entity);
            LoadDesignAsset("button_hl", _config.Design.ButtonHighlight, server, entity);
        }

        private void LoadDesignAsset(string key, string file, FileStorage server, CommunityEntity entity)
        {
            if (string.IsNullOrEmpty(file)) return;
            var full = Path.Combine(DataDesign, file);
            if (!File.Exists(full))
            {
                PrintWarning($"Design file missing: {full} - run design_generator.py.");
                return;
            }

            try
            {
                var bytes = File.ReadAllBytes(full);
                var crc = server.Store(bytes, FileStorage.Type.png, entity.net.ID);
                if (crc != 0) _designPng[key] = crc.ToString();
            }
            catch (Exception e)
            {
                PrintError($"Failed to load design file {full}: {e.Message}");
            }
        }

        private void RegisterRemoteImages()
        {
            if (ImageLibrary == null)
            {
                PrintWarning("ImageLibrary is not loaded - skin and category icons will fall back to colour fills.");
                return;
            }

            foreach (var cat in _catalog.Categories)
            {
                if (!string.IsNullOrEmpty(cat.Icon))
                    ImageLibrary.Call("AddImage", cat.Icon, CategoryImageKey(cat.Shortname), (ulong)0);

                foreach (var skin in cat.Skins)
                {
                    if (string.IsNullOrEmpty(skin.IconUrl)) continue;
                    ImageLibrary.Call("AddImage", skin.IconUrl, SkinImageKey(cat.Shortname, skin.SkinId), (ulong)0);
                }
            }
        }

        private static string SkinImageKey(string shortname, ulong skinId) => $"skin.{shortname}.{skinId}";
        private static string CategoryImageKey(string shortname) => $"cat.{shortname}";

        private string DesignPng(string key) =>
            _designPng.TryGetValue(key, out var id) ? id : null;

        private string RemotePng(string key)
        {
            if (ImageLibrary == null) return null;
            // HasImage avoids returning ImageLibrary's "NO IMAGE FOUND"
            // placeholder while the icon is still downloading.
            try
            {
                var ready = ImageLibrary.Call<bool>("HasImage", key, (ulong)0);
                if (!ready) return null;
            }
            catch (Exception) { /* older ImageLibrary versions */ }
            var result = ImageLibrary.Call<string>("GetImage", key, (ulong)0, false);
            return string.IsNullOrEmpty(result) || result == "0" ? null : result;
        }

        // -------------------------------------------------------------------
        // Commands
        // -------------------------------------------------------------------

        private void CmdMenu(BasePlayer player, string command, string[] args)
        {
            if (!permission.UserHasPermission(player.UserIDString, PermUse))
            {
                player.ChatMessage("You don't have permission to use the skin menu.");
                return;
            }

            OpenMain(player);
        }

        [ConsoleCommand("skinmenu.ui")]
        private void CmdUi(ConsoleSystem.Arg arg)
        {
            var player = arg?.Player();
            if (player == null || !arg.HasArgs(1)) return;
            if (!permission.UserHasPermission(player.UserIDString, PermUse)) return;

            var action = arg.GetString(0);
            switch (action)
            {
                case "close":
                    CloseAll(player);
                    break;

                case "category":
                    HandleCategory(player, arg.GetInt(1, 0));
                    break;

                case "page":
                    HandlePage(player, arg.GetInt(1, 0));
                    break;

                case "pick":
                    HandlePick(player, arg.GetString(1), arg.GetULong(2, 0));
                    break;

                case "create":
                    PromptSetName(player, "Create new set", "create.confirm");
                    break;

                case "create.confirm":
                    HandleCreate(player, JoinFrom(arg, 1));
                    break;

                case "save":
                    HandleSave(player);
                    break;

                case "apply":
                    HandleApply(player);
                    break;

                case "sets":
                    OpenSetList(player);
                    break;

                case "sets.close":
                    CuiHelper.DestroyUi(player, ListPanel);
                    break;

                case "set.load":
                    HandleLoadSet(player, JoinFrom(arg, 1));
                    break;

                case "set.enable":
                    HandleEnableSet(player, JoinFrom(arg, 1));
                    break;

                case "set.delete":
                    HandleDeleteSet(player, JoinFrom(arg, 1));
                    break;

                case "prompt.close":
                    CuiHelper.DestroyUi(player, PromptPanel);
                    break;
            }
        }

        private static string JoinFrom(ConsoleSystem.Arg arg, int start)
        {
            if (arg.Args == null || arg.Args.Length <= start) return string.Empty;
            return string.Join(" ", arg.Args.Skip(start));
        }

        // -------------------------------------------------------------------
        // Menu handlers
        // -------------------------------------------------------------------

        private EditorState Editor(BasePlayer p)
        {
            if (!_editors.TryGetValue(p.userID, out var st))
            {
                st = new EditorState();
                var data = LoadPlayer(p.userID);
                var active = data.Sets.FirstOrDefault(s => s.Name == data.ActiveSet);
                if (active != null)
                {
                    foreach (var kv in active.Items) st.Selection[kv.Key] = kv.Value;
                    st.EditingSetName = active.Name;
                }
                _editors[p.userID] = st;
            }
            return st;
        }

        private void HandleCategory(BasePlayer p, int idx)
        {
            var st = Editor(p);
            st.CategoryIndex = Math.Max(0, Math.Min(idx, _catalog.Categories.Count - 1));
            st.Page = 0;
            OpenMain(p);
        }

        private void HandlePage(BasePlayer p, int delta)
        {
            var st = Editor(p);
            var skins = FilterSkins(_catalog.Categories[st.CategoryIndex]);
            var perPage = Math.Max(1, _config.SkinsPerPage);
            var maxPage = Math.Max(0, (skins.Count - 1) / perPage);
            st.Page = Mathf.Clamp(st.Page + delta, 0, maxPage);
            OpenMain(p);
        }

        private void HandlePick(BasePlayer p, string shortname, ulong skinId)
        {
            var st = Editor(p);
            st.Selection[shortname] = skinId;
            OpenMain(p);
        }

        private void HandleCreate(BasePlayer p, string name)
        {
            name = (name ?? string.Empty).Trim();
            if (name.Length == 0) { p.ChatMessage("Set name cannot be empty."); return; }

            var data = LoadPlayer(p.userID);
            if (data.Sets.Any(s => string.Equals(s.Name, name, StringComparison.OrdinalIgnoreCase)))
            {
                p.ChatMessage($"You already have a set named '{name}'.");
                return;
            }

            var st = Editor(p);
            var now = DateTimeOffset.UtcNow.ToUnixTimeSeconds();
            data.Sets.Add(new SkinSet
            {
                Name = name,
                Items = new Dictionary<string, ulong>(st.Selection),
                CreatedAt = now,
                UpdatedAt = now,
            });
            data.ActiveSet = name;
            st.EditingSetName = name;
            SavePlayer(p.userID);

            CuiHelper.DestroyUi(p, PromptPanel);
            p.ChatMessage($"Created skin set '{name}'.");
            OpenMain(p);
        }

        private void HandleSave(BasePlayer p)
        {
            var st = Editor(p);
            if (string.IsNullOrEmpty(st.EditingSetName))
            {
                p.ChatMessage("No active set - press 'Create set' first.");
                return;
            }

            var data = LoadPlayer(p.userID);
            var set = data.Sets.FirstOrDefault(s =>
                string.Equals(s.Name, st.EditingSetName, StringComparison.OrdinalIgnoreCase));
            if (set == null)
            {
                p.ChatMessage($"Set '{st.EditingSetName}' no longer exists.");
                return;
            }

            set.Items = new Dictionary<string, ulong>(st.Selection);
            set.UpdatedAt = DateTimeOffset.UtcNow.ToUnixTimeSeconds();
            SavePlayer(p.userID);
            p.ChatMessage($"Saved skin set '{set.Name}'.");
        }

        private void HandleApply(BasePlayer p)
        {
            var st = Editor(p);
            var temp = new SkinSet { Name = st.EditingSetName ?? "<draft>", Items = st.Selection };
            ApplySetToInventory(p, temp);
            p.ChatMessage("Applied current selection to your inventory items.");
        }

        private void HandleLoadSet(BasePlayer p, string name)
        {
            var data = LoadPlayer(p.userID);
            var set = data.Sets.FirstOrDefault(s =>
                string.Equals(s.Name, name, StringComparison.OrdinalIgnoreCase));
            if (set == null) return;

            var st = Editor(p);
            st.Selection = new Dictionary<string, ulong>(set.Items);
            st.EditingSetName = set.Name;
            data.ActiveSet = set.Name;
            SavePlayer(p.userID);
            CuiHelper.DestroyUi(p, ListPanel);
            OpenMain(p);
        }

        private void HandleEnableSet(BasePlayer p, string name)
        {
            var data = LoadPlayer(p.userID);
            var set = data.Sets.FirstOrDefault(s =>
                string.Equals(s.Name, name, StringComparison.OrdinalIgnoreCase));
            if (set == null) return;
            data.ActiveSet = set.Name;
            SavePlayer(p.userID);
            ApplySetToInventory(p, set);
            p.ChatMessage($"Enabled set '{set.Name}'.");
        }

        private void HandleDeleteSet(BasePlayer p, string name)
        {
            var data = LoadPlayer(p.userID);
            var removed = data.Sets.RemoveAll(s =>
                string.Equals(s.Name, name, StringComparison.OrdinalIgnoreCase));
            if (removed > 0)
            {
                if (string.Equals(data.ActiveSet, name, StringComparison.OrdinalIgnoreCase))
                    data.ActiveSet = null;
                SavePlayer(p.userID);
                p.ChatMessage($"Deleted set '{name}'.");
            }
            OpenSetList(p);
        }

        // -------------------------------------------------------------------
        // Inventory apply
        // -------------------------------------------------------------------

        private void ApplySetToInventory(BasePlayer p, SkinSet set)
        {
            if (p == null || p.inventory == null || set == null) return;

            foreach (var container in new[] { p.inventory.containerMain, p.inventory.containerBelt, p.inventory.containerWear })
            {
                if (container == null) continue;
                foreach (var item in container.itemList)
                {
                    if (item == null || item.info == null) continue;
                    if (!set.Items.TryGetValue(item.info.shortname, out var skin)) continue;

                    item.skin = skin;
                    item.MarkDirty();
                    var held = item.GetHeldEntity();
                    if (held != null)
                    {
                        held.skinID = skin;
                        held.SendNetworkUpdate();
                    }
                }
            }
        }

        // -------------------------------------------------------------------
        // UI helpers
        // -------------------------------------------------------------------

        private const string ColAccent = "0.18 0.56 0.88 1";
        private const string ColAccentSoft = "0.18 0.56 0.88 0.7";
        private const string ColPanel = "0.12 0.13 0.16 0.95";
        private const string ColSlot = "0.16 0.17 0.20 0.95";
        private const string ColRow = "0.18 0.19 0.22 0.95";
        private const string ColDanger = "0.70 0.18 0.18 0.95";
        private const string ColSuccess = "0.20 0.62 0.32 0.95";
        private const string ColTransparent = "0 0 0 0";

        private static string Coord(float x, float y) =>
            x.ToString("0.####", System.Globalization.CultureInfo.InvariantCulture) + " " +
            y.ToString("0.####", System.Globalization.CultureInfo.InvariantCulture);

        private void AddStyledButton(CuiElementContainer elements, string parent,
            string text, string command,
            float xMin, float yMin, float xMax, float yMax,
            bool highlighted = false, string altColor = null, int fontSize = 13)
        {
            var pngKey = highlighted ? "button_hl" : "button";
            var png = DesignPng(pngKey);

            // When a custom design PNG is present, draw the PNG first
            // and put the button overlay on top as a transparent click
            // target so the design shows through.
            string buttonColor;
            if (!string.IsNullOrEmpty(png))
            {
                elements.Add(new CuiElement
                {
                    Parent = parent,
                    Components =
                    {
                        new CuiRawImageComponent { Png = png, Color = "1 1 1 1" },
                        new CuiRectTransformComponent
                        {
                            AnchorMin = Coord(xMin, yMin),
                            AnchorMax = Coord(xMax, yMax),
                        }
                    }
                });
                buttonColor = altColor ?? ColTransparent;
            }
            else
            {
                buttonColor = altColor ?? (highlighted ? ColAccent : "0.22 0.23 0.26 0.95");
            }

            elements.Add(new CuiButton
            {
                Button = { Color = buttonColor, Command = command },
                Text = { Text = text ?? string.Empty, FontSize = fontSize,
                         Align = TextAnchor.MiddleCenter, Color = "1 1 1 1" },
                RectTransform =
                {
                    AnchorMin = Coord(xMin, yMin),
                    AnchorMax = Coord(xMax, yMax),
                },
            }, parent);
        }

        private void AddRawImage(CuiElementContainer elements, string parent, string png,
                                 float xMin, float yMin, float xMax, float yMax)
        {
            if (string.IsNullOrEmpty(png)) return;
            elements.Add(new CuiElement
            {
                Parent = parent,
                Components =
                {
                    new CuiRawImageComponent { Png = png, Color = "1 1 1 1" },
                    new CuiRectTransformComponent
                    {
                        AnchorMin = Coord(xMin, yMin),
                        AnchorMax = Coord(xMax, yMax),
                    }
                }
            });
        }

        // -------------------------------------------------------------------
        // Main menu
        // -------------------------------------------------------------------

        private void CloseAll(BasePlayer p)
        {
            CuiHelper.DestroyUi(p, MainPanel);
            CuiHelper.DestroyUi(p, ListPanel);
            CuiHelper.DestroyUi(p, PromptPanel);
            _editors.Remove(p.userID);
        }

        private void OpenMain(BasePlayer p)
        {
            CuiHelper.DestroyUi(p, MainPanel);

            var st = Editor(p);
            if (_catalog.Categories.Count == 0)
            {
                p.ChatMessage("Skin catalog is empty - edit data/SkinMenu/skins.json on the server.");
                return;
            }

            st.CategoryIndex = Mathf.Clamp(st.CategoryIndex, 0, _catalog.Categories.Count - 1);
            var category = _catalog.Categories[st.CategoryIndex];
            var skins = FilterSkins(category);
            var perPage = Math.Max(1, _config.SkinsPerPage);
            var totalPages = Math.Max(1, (int)Math.Ceiling(skins.Count / (double)perPage));
            st.Page = Mathf.Clamp(st.Page, 0, totalPages - 1);

            var elements = new CuiElementContainer();
            BuildOverlay(elements);
            BuildFrame(elements);
            BuildHeader(elements, category, st.Page, totalPages);
            BuildCategoryColumn(elements, st);
            BuildSkinGrid(elements, category, skins, st, perPage, totalPages);
            BuildActionButtons(elements, st);
            BuildFooter(elements);

            CuiHelper.AddUi(p, elements);
        }

        // Full-screen click-blocker that holds the cursor.
        private void BuildOverlay(CuiElementContainer elements)
        {
            elements.Add(new CuiPanel
            {
                Image = { Color = "0 0 0 0.65" },
                RectTransform = { AnchorMin = "0 0", AnchorMax = "1 1" },
                CursorEnabled = true,
            }, "Overlay", MainPanel);
        }

        // Inner panel: 60% wide x 80% tall, centered.
        private void BuildFrame(CuiElementContainer elements)
        {
            elements.Add(new CuiPanel
            {
                Image = { Color = ColPanel },
                RectTransform = { AnchorMin = "0.20 0.10", AnchorMax = "0.80 0.90" },
            }, MainPanel, FramePanel);

            var bg = DesignPng("bg");
            if (!string.IsNullOrEmpty(bg))
            {
                AddRawImage(elements, FramePanel, bg, 0f, 0f, 1f, 1f);
            }
        }

        private void BuildHeader(CuiElementContainer elements, CatalogCategory cat, int page, int totalPages)
        {
            elements.Add(new CuiLabel
            {
                Text =
                {
                    Text = "<b>SKIN MENU</b>",
                    FontSize = 18, Align = TextAnchor.MiddleLeft, Color = "1 1 1 1",
                },
                RectTransform = { AnchorMin = "0.03 0.93", AnchorMax = "0.50 0.99" },
            }, FramePanel);

            elements.Add(new CuiLabel
            {
                Text =
                {
                    Text = $"{cat.Display}  -  page {page + 1}/{totalPages}",
                    FontSize = 12, Align = TextAnchor.MiddleRight, Color = "0.85 0.85 0.85 1",
                },
                RectTransform = { AnchorMin = "0.50 0.93", AnchorMax = "0.92 0.99" },
            }, FramePanel);

            AddStyledButton(elements, FramePanel, "X", "skinmenu.ui close",
                0.94f, 0.935f, 0.985f, 0.985f,
                altColor: ColDanger, fontSize: 14);
        }

        // Left column: vertical list of categories with icons.
        private void BuildCategoryColumn(CuiElementContainer elements, EditorState st)
        {
            const float left = 0.03f;
            const float right = 0.30f;
            const float top = 0.90f;
            const float bot = 0.30f;

            elements.Add(new CuiPanel
            {
                Image = { Color = ColSlot },
                RectTransform =
                {
                    AnchorMin = Coord(left, bot),
                    AnchorMax = Coord(right, top),
                },
            }, FramePanel, FramePanel + ".cats");

            var rows = _catalog.Categories.Count;
            if (rows == 0) return;

            const float headerH = 0.06f;
            elements.Add(new CuiLabel
            {
                Text =
                {
                    Text = "Categories", FontSize = 12,
                    Align = TextAnchor.MiddleCenter, Color = "0.85 0.85 0.85 1",
                },
                RectTransform =
                {
                    AnchorMin = $"0 {1f - headerH}",
                    AnchorMax = "1 1",
                },
            }, FramePanel + ".cats");

            // Reserve top portion for header, rest is for rows.
            var listTop = 1f - headerH;
            var rowSpan = listTop / Mathf.Max(1, rows);

            for (var i = 0; i < rows; i++)
            {
                var rowTop = listTop - i * rowSpan;
                var rowBot = rowTop - rowSpan + 0.005f;
                var rowName = FramePanel + ".cats.row" + i;
                var active = i == st.CategoryIndex;

                // Card background: design PNG if available, else flat colour.
                var card = DesignPng(active ? "slot_active" : "slot");
                if (!string.IsNullOrEmpty(card))
                {
                    elements.Add(new CuiElement
                    {
                        Parent = FramePanel + ".cats",
                        Name = rowName,
                        Components =
                        {
                            new CuiRawImageComponent { Png = card, Color = "1 1 1 1" },
                            new CuiRectTransformComponent
                            {
                                AnchorMin = $"0.04 {rowBot}",
                                AnchorMax = $"0.96 {rowTop - 0.005f}",
                            }
                        }
                    });
                }
                else
                {
                    elements.Add(new CuiPanel
                    {
                        Image = { Color = active ? ColAccentSoft : ColRow },
                        RectTransform =
                        {
                            AnchorMin = $"0.04 {rowBot}",
                            AnchorMax = $"0.96 {rowTop - 0.005f}",
                        },
                    }, FramePanel + ".cats", rowName);
                }

                // Icon on the left of the row when ImageLibrary has it.
                var icon = RemotePng(CategoryImageKey(_catalog.Categories[i].Shortname));
                var hasIcon = !string.IsNullOrEmpty(icon);
                if (hasIcon)
                {
                    AddRawImage(elements, rowName, icon, 0.04f, 0.10f, 0.32f, 0.90f);
                }

                // Display label. Center it when there's no icon so the
                // ImageLibrary "NO IMAGE FOUND" placeholder is never visible.
                elements.Add(new CuiLabel
                {
                    Text =
                    {
                        Text = _catalog.Categories[i].Display ?? _catalog.Categories[i].Shortname,
                        FontSize = 13,
                        Align = hasIcon ? TextAnchor.MiddleLeft : TextAnchor.MiddleCenter,
                        Color = "1 1 1 1",
                    },
                    RectTransform =
                    {
                        AnchorMin = hasIcon ? "0.36 0" : "0.05 0",
                        AnchorMax = "0.98 1",
                    },
                }, rowName);

                // Click-cover button.
                elements.Add(new CuiButton
                {
                    Button = { Color = ColTransparent, Command = $"skinmenu.ui category {i}" },
                    Text = { Text = string.Empty },
                    RectTransform = { AnchorMin = "0 0", AnchorMax = "1 1" },
                }, rowName);
            }
        }

        // Right side: 4-column square skin grid with pagination arrows.
        private void BuildSkinGrid(CuiElementContainer elements, CatalogCategory cat,
                                   List<CatalogSkin> skins, EditorState st,
                                   int perPage, int totalPages)
        {
            const float gridLeft = 0.33f;
            const float gridRight = 0.97f;
            const float gridTop = 0.90f;
            const float gridBot = 0.30f;
            const int cols = 4;

            var rowsPerPage = Math.Max(1, perPage / cols);

            var areaWidth = gridRight - gridLeft;
            var cellPitchX = areaWidth / cols;
            // Slot is slightly smaller than the cell to leave padding.
            var slotWidth = cellPitchX * 0.92f;
            var slotHeight = slotWidth * FrameSquareYPerX;
            var cellPitchY = slotHeight / 0.92f;
            var gridHeight = cellPitchY * rowsPerPage;
            var gridStartY = Mathf.Min(gridTop, gridBot + gridHeight + (gridTop - gridBot - gridHeight) * 0.5f);

            var selectedSkin = st.Selection.TryGetValue(cat.Shortname, out var s) ? s : 0UL;
            var startIdx = st.Page * perPage;

            for (var i = 0; i < perPage; i++)
            {
                var idx = startIdx + i;
                if (idx >= skins.Count) break;
                var skin = skins[idx];
                var col = i % cols;
                var row = i / cols;

                var cellCenterX = gridLeft + (col + 0.5f) * cellPitchX;
                var xMin = cellCenterX - slotWidth * 0.5f;
                var xMax = cellCenterX + slotWidth * 0.5f;
                var cellCenterY = gridStartY - (row + 0.5f) * cellPitchY;
                var yMin = cellCenterY - slotHeight * 0.5f;
                var yMax = cellCenterY + slotHeight * 0.5f;

                var slotName = FramePanel + ".slot." + i;
                var isActive = skin.SkinId == selectedSkin;

                elements.Add(new CuiPanel
                {
                    Image = { Color = isActive ? ColAccentSoft : ColSlot },
                    RectTransform = { AnchorMin = Coord(xMin, yMin), AnchorMax = Coord(xMax, yMax) },
                }, FramePanel, slotName);

                var frame = DesignPng(isActive ? "slot_active" : "slot");
                if (!string.IsNullOrEmpty(frame))
                {
                    AddRawImage(elements, slotName, frame, 0f, 0f, 1f, 1f);
                }

                var iconImg = RemotePng(SkinImageKey(cat.Shortname, skin.SkinId));
                if (!string.IsNullOrEmpty(iconImg))
                {
                    AddRawImage(elements, slotName, iconImg, 0.10f, 0.22f, 0.90f, 0.95f);
                }

                elements.Add(new CuiLabel
                {
                    Text =
                    {
                        Text = skin.Name ?? skin.SkinId.ToString(),
                        FontSize = 10, Align = TextAnchor.MiddleCenter, Color = "1 1 1 1",
                    },
                    RectTransform = { AnchorMin = "0 0.02", AnchorMax = "1 0.20" },
                }, slotName);

                elements.Add(new CuiButton
                {
                    Button = { Color = ColTransparent, Command = $"skinmenu.ui pick {cat.Shortname} {skin.SkinId}" },
                    Text = { Text = string.Empty },
                    RectTransform = { AnchorMin = "0 0", AnchorMax = "1 1" },
                }, slotName);
            }

            // Pagination arrows.
            const float arrowY = 0.30f;
            AddStyledButton(elements, FramePanel, "\u25C0", "skinmenu.ui page -1",
                gridLeft, arrowY, gridLeft + 0.04f, arrowY + 0.04f,
                fontSize: 14);
            AddStyledButton(elements, FramePanel, "\u25B6", "skinmenu.ui page 1",
                gridRight - 0.04f, arrowY, gridRight, arrowY + 0.04f,
                fontSize: 14);

            elements.Add(new CuiLabel
            {
                Text =
                {
                    Text = $"{st.Page + 1} / {totalPages}",
                    FontSize = 11, Align = TextAnchor.MiddleCenter, Color = "0.85 0.85 0.85 1",
                },
                RectTransform = { AnchorMin = Coord(gridLeft + 0.05f, arrowY),
                                  AnchorMax = Coord(gridRight - 0.05f, arrowY + 0.04f) },
            }, FramePanel);
        }

        // Three buttons below the grid + active-set label.
        private void BuildActionButtons(CuiElementContainer elements, EditorState st)
        {
            var labels = new[] { "Create set", "Save set", "Enable set" };
            var cmds = new[] { "skinmenu.ui create", "skinmenu.ui save", "skinmenu.ui apply" };

            const float left = 0.33f;
            const float right = 0.97f;
            const float top = 0.22f;
            const float bot = 0.15f;
            var width = (right - left) / labels.Length;

            for (var i = 0; i < labels.Length; i++)
            {
                var xMin = left + i * width + 0.005f;
                var xMax = left + (i + 1) * width - 0.005f;
                AddStyledButton(elements, FramePanel, labels[i], cmds[i],
                    xMin, bot, xMax, top, highlighted: true, fontSize: 13);
            }

            var active = string.IsNullOrEmpty(st.EditingSetName) ? "<i>(no active set)</i>" : $"<b>{st.EditingSetName}</b>";
            elements.Add(new CuiLabel
            {
                Text =
                {
                    Text = "Active set: " + active, FontSize = 12,
                    Align = TextAnchor.MiddleCenter, Color = "0.85 0.85 0.85 1",
                },
                RectTransform = { AnchorMin = Coord(left, 0.105f), AnchorMax = Coord(right, 0.145f) },
            }, FramePanel);
        }

        private void BuildFooter(CuiElementContainer elements)
        {
            AddStyledButton(elements, FramePanel, "All sets", "skinmenu.ui sets",
                0.40f, 0.04f, 0.60f, 0.10f, fontSize: 13);
        }

        // -------------------------------------------------------------------
        // Set list panel
        // -------------------------------------------------------------------

        private void OpenSetList(BasePlayer p)
        {
            CuiHelper.DestroyUi(p, ListPanel);

            var data = LoadPlayer(p.userID);
            var elements = new CuiElementContainer();

            elements.Add(new CuiPanel
            {
                Image = { Color = "0 0 0 0.65" },
                RectTransform = { AnchorMin = "0 0", AnchorMax = "1 1" },
                CursorEnabled = true,
            }, "Overlay", ListPanel);

            elements.Add(new CuiPanel
            {
                Image = { Color = ColPanel },
                RectTransform = { AnchorMin = "0.30 0.20", AnchorMax = "0.70 0.85" },
            }, ListPanel, ListPanel + ".inner");

            elements.Add(new CuiLabel
            {
                Text =
                {
                    Text = "<b>YOUR SKIN SETS</b>", FontSize = 16,
                    Align = TextAnchor.MiddleCenter, Color = "1 1 1 1",
                },
                RectTransform = { AnchorMin = "0 0.92", AnchorMax = "1 0.99" },
            }, ListPanel + ".inner");

            AddStyledButton(elements, ListPanel + ".inner", "X", "skinmenu.ui sets.close",
                0.93f, 0.93f, 0.99f, 0.99f, altColor: ColDanger, fontSize: 13);

            if (data.Sets.Count == 0)
            {
                elements.Add(new CuiLabel
                {
                    Text =
                    {
                        Text = "You have no sets yet. Press <b>Create set</b> in the main menu.",
                        FontSize = 12, Align = TextAnchor.MiddleCenter, Color = "0.85 0.85 0.85 1",
                    },
                    RectTransform = { AnchorMin = "0.05 0.5", AnchorMax = "0.95 0.6" },
                }, ListPanel + ".inner");
            }
            else
            {
                const float top = 0.88f;
                const float rowH = 0.085f;
                var maxRows = Math.Min(9, data.Sets.Count);
                for (var i = 0; i < maxRows; i++)
                {
                    var set = data.Sets[i];
                    var yMax = top - i * rowH;
                    var yMin = yMax - rowH + 0.005f;
                    var rowName = ListPanel + ".row." + i;

                    elements.Add(new CuiPanel
                    {
                        Image = { Color = ColRow },
                        RectTransform = { AnchorMin = Coord(0.05f, yMin), AnchorMax = Coord(0.95f, yMax) },
                    }, ListPanel + ".inner", rowName);

                    elements.Add(new CuiLabel
                    {
                        Text =
                        {
                            Text = $"{set.Name}  <color=#888>({set.Items.Count} items)</color>",
                            FontSize = 13, Align = TextAnchor.MiddleLeft, Color = "1 1 1 1",
                        },
                        RectTransform = { AnchorMin = "0.03 0", AnchorMax = "0.50 1" },
                    }, rowName);

                    AddStyledButton(elements, rowName, "Load", $"skinmenu.ui set.load {set.Name}",
                        0.52f, 0.15f, 0.66f, 0.85f, highlighted: true, fontSize: 11);
                    AddStyledButton(elements, rowName, "Enable", $"skinmenu.ui set.enable {set.Name}",
                        0.68f, 0.15f, 0.82f, 0.85f, altColor: ColSuccess, fontSize: 11);
                    AddStyledButton(elements, rowName, "Delete", $"skinmenu.ui set.delete {set.Name}",
                        0.84f, 0.15f, 0.97f, 0.85f, altColor: ColDanger, fontSize: 11);
                }
            }

            CuiHelper.AddUi(p, elements);
        }

        // -------------------------------------------------------------------
        // Set-name prompt
        // -------------------------------------------------------------------

        private void PromptSetName(BasePlayer p, string title, string confirmAction)
        {
            CuiHelper.DestroyUi(p, PromptPanel);
            var elements = new CuiElementContainer();

            elements.Add(new CuiPanel
            {
                Image = { Color = "0 0 0 0.6" },
                RectTransform = { AnchorMin = "0 0", AnchorMax = "1 1" },
                CursorEnabled = true,
            }, "Overlay", PromptPanel);

            elements.Add(new CuiPanel
            {
                Image = { Color = ColPanel },
                RectTransform = { AnchorMin = "0.38 0.42", AnchorMax = "0.62 0.58" },
            }, PromptPanel, PromptPanel + ".inner");

            elements.Add(new CuiLabel
            {
                Text =
                {
                    Text = title, FontSize = 14,
                    Align = TextAnchor.MiddleCenter, Color = "1 1 1 1",
                },
                RectTransform = { AnchorMin = "0 0.78", AnchorMax = "1 0.98" },
            }, PromptPanel + ".inner");

            // Input is a child element with both an image background and
            // an input field component on the same CuiElement.
            elements.Add(new CuiPanel
            {
                Image = { Color = "0.20 0.20 0.24 0.95" },
                RectTransform = { AnchorMin = "0.10 0.40", AnchorMax = "0.90 0.70" },
            }, PromptPanel + ".inner", PromptPanel + ".input");

            elements.Add(new CuiElement
            {
                Parent = PromptPanel + ".input",
                Components =
                {
                    new CuiInputFieldComponent
                    {
                        FontSize = 14,
                        Align = TextAnchor.MiddleCenter,
                        Color = "1 1 1 1",
                        CharsLimit = 24,
                        Command = "skinmenu.ui " + confirmAction + " ",
                        IsPassword = false,
                        NeedsKeyboard = true,
                    },
                    new CuiRectTransformComponent { AnchorMin = "0 0", AnchorMax = "1 1" }
                }
            });

            AddStyledButton(elements, PromptPanel + ".inner", "Cancel", "skinmenu.ui prompt.close",
                0.55f, 0.10f, 0.90f, 0.32f, altColor: ColDanger, fontSize: 11);

            elements.Add(new CuiLabel
            {
                Text =
                {
                    Text = "<size=10>Type a name and press Enter</size>",
                    FontSize = 10, Align = TextAnchor.MiddleLeft, Color = "0.7 0.7 0.7 1",
                },
                RectTransform = { AnchorMin = "0.10 0.10", AnchorMax = "0.55 0.32" },
            }, PromptPanel + ".inner");

            CuiHelper.AddUi(p, elements);
        }
    }
}
